# Generated by Django 3.2.6 on 2021-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=50)),
                ('FileSize', models.CharField(max_length=50)),
                ('FileUrl', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
