# Generated by Django 3.2.7 on 2021-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription', models.CharField(choices=[('S', 'Subscribed'), ('N', 'Unsubscribed')], max_length=1, verbose_name='subscription')),
                ('stripeCustomerId', models.CharField(max_length=255, verbose_name='stripe user id')),
                ('stripeSubscriptionId', models.CharField(max_length=255, verbose_name='stripe subscription id')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=50)),
                ('FileSize', models.CharField(max_length=50)),
                ('FileUrl', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
